services:
  conciliacao-api:
    image: sleepykamigami/conci-gca:latest
    environment:
      # Configurações do Banco de Dados - usar variáveis de ambiente
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER:-ODBC Driver 17 for SQL Server} 
      # Configurações FTP - usar variáveis de ambiente
      - FTP_HOST=${FTP_HOST}
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - FTP_PORT=${FTP_PORT:-21}
      # Configurações Flask
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    volumes:
      - logs-prod:/app/logs

    networks:
      - network_swarm_public
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
networks:
  network_swarm_public:
    external: true
volumes:
  logs-prod:
    external: true
    name: conciliacao-logs-prod
